from tkinter import *
import datetime
root = Tk()
root.title('To-Do List')
root.geometry('300x500')
root.resizable(0, 0)
root.config(bg="aqua")
title=Label(root,text="To-Dooo list",font=('Helvetica','18'))
frame1=Frame(root,width=100)
frame1.grid(rows=2,padx=20,pady=20,column=0,ipadx=20,ipady=20)
mytext1=Entry(frame1,font=16,)
mytext1.grid(row=0,column=0)
var1=IntVar()
check=Checkbutton(frame1, text="")
check.grid(row=0,column=1)
mytext2=Entry(frame1,font=16)
mytext2.grid(row=1,column=0)
var2=IntVar()
check1=Checkbutton(frame1, text="")
check1.grid(row=1,column=1)
mytext3=Entry(frame1,font=16)
mytext3.grid(row=2,column=0)
var2=IntVar()
check2=Checkbutton(frame1, text="")
check2.grid(row=2,column=1)
mytext4=Entry(frame1,font=16)
mytext4.grid(row=3,column=0)
var2=IntVar()
check3=Checkbutton(frame1, text="")
check3.grid(row=3,column=1)
mytext4=Entry(frame1,font=16)
mytext4.grid(row=4,column=0)
var2=IntVar()
check4=Checkbutton(frame1, text="")
check4.grid(row=4,column=1)
mytext5=Entry(frame1,font=16)
mytext5.grid(row=5,column=0)
var2=IntVar()
check6=Checkbutton(frame1, text="")
check6.grid(row=5,column=1)
mytext6=Entry(frame1,font=16)
mytext6.grid(row=6,column=0)
var2=IntVar()
check7=Checkbutton(frame1, text="")
check7.grid(row=6,column=1)
mytext7=Entry(frame1,font=16)
mytext7.grid(row=7,column=0)
var2=IntVar()
check8=Checkbutton(frame1, text="")
check8.grid(row=7,column=1)
mytext8=Entry(frame1,font=16)
mytext8.grid(row=8,column=0)
var2=IntVar()
check9=Checkbutton(frame1, text="")
check9.grid(row=8,column=1)
mytext9=Entry(frame1,font=16)
mytext9.grid(row=9,column=0)
var2=IntVar()
check10=Checkbutton(frame1, text="")
check10.grid(row=9,column=1)
exit=Button(frame1, text="all tasks checked",command=root.destroy)
exit.grid()
frame1.pack()
text=Label(root, text="TASKS",bg="red",fg="yellow")
text.pack(fill="both")
title.pack()
root.mainloop()


